/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    projects: Project;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    projects: ProjectsSelect<false> | ProjectsSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'home-page': HomePage;
    'houses-page': HousesPage;
    'baths-page': BathsPage;
    'production-page': ProductionPage;
    'warranty-page': WarrantyPage;
    'delivery-page': DeliveryPage;
    'custom-design-page': CustomDesignPage;
    'contacts-page': ContactsPage;
    'site-settings': SiteSetting;
  };
  globalsSelect: {
    'home-page': HomePageSelect<false> | HomePageSelect<true>;
    'houses-page': HousesPageSelect<false> | HousesPageSelect<true>;
    'baths-page': BathsPageSelect<false> | BathsPageSelect<true>;
    'production-page': ProductionPageSelect<false> | ProductionPageSelect<true>;
    'warranty-page': WarrantyPageSelect<false> | WarrantyPageSelect<true>;
    'delivery-page': DeliveryPageSelect<false> | DeliveryPageSelect<true>;
    'custom-design-page': CustomDesignPageSelect<false> | CustomDesignPageSelect<true>;
    'contacts-page': ContactsPageSelect<false> | ContactsPageSelect<true>;
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  caption?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects".
 */
export interface Project {
  id: number;
  title: string;
  slug: string;
  projectNo: string;
  kind: 'house' | 'bath';
  summary: string;
  feature: string;
  rooms: string;
  bedrooms: number;
  area: string;
  size: string;
  terrace?: string | null;
  priceWarm?: string | null;
  priceTurnkey: string;
  priceNote?: string | null;
  singleColumn?: boolean | null;
  image?: (number | null) | Media;
  plan?: (number | null) | Media;
  legacyImagePath?: string | null;
  legacyPlanPath?: string | null;
  layoutDescription: string;
  suitableFor: string;
  highlights?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  specs?:
    | {
        label: string;
        warm?: string | null;
        turnkey: string;
        id?: string | null;
      }[]
    | null;
  seoTitle: string;
  seoDescription: string;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'projects';
        value: number | Project;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "projects_select".
 */
export interface ProjectsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  projectNo?: T;
  kind?: T;
  summary?: T;
  feature?: T;
  rooms?: T;
  bedrooms?: T;
  area?: T;
  size?: T;
  terrace?: T;
  priceWarm?: T;
  priceTurnkey?: T;
  priceNote?: T;
  singleColumn?: T;
  image?: T;
  plan?: T;
  legacyImagePath?: T;
  legacyPlanPath?: T;
  layoutDescription?: T;
  suitableFor?: T;
  highlights?:
    | T
    | {
        text?: T;
        id?: T;
      };
  specs?:
    | T
    | {
        label?: T;
        warm?: T;
        turnkey?: T;
        id?: T;
      };
  seoTitle?: T;
  seoDescription?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page".
 */
export interface HomePage {
  id: number;
  /**
   * Структурированные тексты всех секций главной страницы. Проекты берутся из отдельного раздела «Проекты домов и бань».
   */
  contentRu:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  contentEn:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  aboutKitchenImage?: (number | null) | Media;
  aboutBedroomImage?: (number | null) | Media;
  completedProjects?:
    | {
        titleRu: string;
        titleEn: string;
        metaRu: string;
        metaEn: string;
        textRu: string;
        textEn: string;
        quote?: string | null;
        images: (number | Media)[];
        id?: string | null;
      }[]
    | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "houses-page".
 */
export interface HousesPage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  eyebrow: string;
  title: string;
  lead: string;
  introTitle: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  catalogTitle: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "baths-page".
 */
export interface BathsPage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  eyebrow: string;
  title: string;
  lead: string;
  introTitle: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  benefits?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  catalogTitle: string;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-page".
 */
export interface ProductionPage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  eyebrow: string;
  title: string;
  lead: string;
  introTitle: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        text: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle: string;
  ctaText: string;
  showContacts?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranty-page".
 */
export interface WarrantyPage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  eyebrow: string;
  title: string;
  lead: string;
  introTitle: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        text: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle: string;
  ctaText: string;
  showContacts?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-page".
 */
export interface DeliveryPage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  eyebrow: string;
  title: string;
  lead: string;
  introTitle: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        text: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle: string;
  ctaText: string;
  showContacts?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-design-page".
 */
export interface CustomDesignPage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  eyebrow: string;
  title: string;
  lead: string;
  introTitle: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        text: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle: string;
  ctaText: string;
  showContacts?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page".
 */
export interface ContactsPage {
  id: number;
  seo: {
    metaTitle: string;
    metaDescription: string;
    ogImage?: (number | null) | Media;
  };
  eyebrow: string;
  title: string;
  lead: string;
  introTitle: string;
  paragraphs?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  sections?:
    | {
        title: string;
        text: string;
        items?:
          | {
              text: string;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  ctaTitle: string;
  ctaText: string;
  showContacts?: boolean | null;
  _status?: ('draft' | 'published') | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  phone: string;
  email: string;
  address: string;
  defaultMetaTitle: string;
  defaultMetaDescription: string;
  socialImage?: (number | null) | Media;
  catalog?: (number | null) | Media;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "home-page_select".
 */
export interface HomePageSelect<T extends boolean = true> {
  contentRu?: T;
  contentEn?: T;
  aboutKitchenImage?: T;
  aboutBedroomImage?: T;
  completedProjects?:
    | T
    | {
        titleRu?: T;
        titleEn?: T;
        metaRu?: T;
        metaEn?: T;
        textRu?: T;
        textEn?: T;
        quote?: T;
        images?: T;
        id?: T;
      };
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "houses-page_select".
 */
export interface HousesPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  eyebrow?: T;
  title?: T;
  lead?: T;
  introTitle?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  catalogTitle?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "baths-page_select".
 */
export interface BathsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  eyebrow?: T;
  title?: T;
  lead?: T;
  introTitle?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  benefits?:
    | T
    | {
        text?: T;
        id?: T;
      };
  catalogTitle?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "production-page_select".
 */
export interface ProductionPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  eyebrow?: T;
  title?: T;
  lead?: T;
  introTitle?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        text?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  showContacts?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "warranty-page_select".
 */
export interface WarrantyPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  eyebrow?: T;
  title?: T;
  lead?: T;
  introTitle?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        text?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  showContacts?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "delivery-page_select".
 */
export interface DeliveryPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  eyebrow?: T;
  title?: T;
  lead?: T;
  introTitle?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        text?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  showContacts?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "custom-design-page_select".
 */
export interface CustomDesignPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  eyebrow?: T;
  title?: T;
  lead?: T;
  introTitle?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        text?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  showContacts?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "contacts-page_select".
 */
export interface ContactsPageSelect<T extends boolean = true> {
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  eyebrow?: T;
  title?: T;
  lead?: T;
  introTitle?: T;
  paragraphs?:
    | T
    | {
        text?: T;
        id?: T;
      };
  sections?:
    | T
    | {
        title?: T;
        text?: T;
        items?:
          | T
          | {
              text?: T;
              id?: T;
            };
        id?: T;
      };
  ctaTitle?: T;
  ctaText?: T;
  showContacts?: T;
  _status?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  phone?: T;
  email?: T;
  address?: T;
  defaultMetaTitle?: T;
  defaultMetaDescription?: T;
  socialImage?: T;
  catalog?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}